[window]
opacity = 0.9
decorations = "transparent"
padding = { x = 0, y = 0 }

[font]
normal = { family = "Hack Nerd Font Propo", style = "Regular" }
size = 14.2
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[colors]
primary = { background = "#2d2f2f" }  # Set based on the theme "Everforest Dark (Gogh)"

[scrolling]
history = 10000

[terminal.shell]
program = "nu"
